### ISSUE TITLE
Remove jquery as dependency? 

### ISSUE THREAD

**Issue by wuarmin** [williamsbdev/ember-cli-focus-input#11]
Hey, 
what do you think about removing jquery as dep (or at least make it optional)?
Nowadays it's possible to disable jquery integration in Ember. So it could be a reason to not use this addon.

**Comment by williamsbdev** [comment]
@wuarmin - that sounds great! Would you submit another PR for it and we’ll get that published. That would require us to go to 3.0.0 just in case someone was expecting jquery to still be there.

**Comment by wuarmin** [comment]
@williamsbdev yes, I'm up for it.

**Comment by williamsbdev** [comment]
@wuarmin - I'm going to close this. If you open up a PR, we'll address it at that point. Thanks!
