### ISSUE TITLE
ember-cli-babel 5.x has been deprecated. Can we create a new Release ?

### ISSUE THREAD

**Issue by wuarmin** [williamsbdev/ember-cli-focus-input#9]
Hello @williamsbdev ,

WDYT about a new release?

kind regards

**Comment by toranb** [comment]
@wuarmin would you want to join up as a contributor? This addon could use some love (Brandon and I no longer use this day to day for work/personal) and I think I could convince him to hand over some access if you are up for it ;)

**Comment by wuarmin** [comment]
@toranb yes, I'm up to it.

**Comment by williamsbdev** [comment]
@wuarmin - Do you have time to put together a PR? If so, I'd take a look at this and get it published.

**Comment by wuarmin** [comment]
@williamsbdev yes, I will provide a PR in the next days.
